language: cpp
compiler:
  #- clang
  - gcc
before_install:
  - sudo apt-get install pkg-config ragel gtk-doc-tools # for autogen.sh
  - sudo apt-get install libfreetype6-dev # for font functions
  - sudo apt-get install libglib2.0-dev # for font functions / tests / utils
  - sudo apt-get install libcairo2-dev # for utils
  - sudo apt-get install libicu-dev # for extra unicode functions
  - sudo apt-get install libgraphite2-dev # for extra shapers
  - sudo pip install cpp-coveralls # for coveralls.io code coverage tracking
install:
  - true
before_script:
  - true
script:
  - NOCONFIGURE=1 ./autogen.sh
  - ./configure --with-freetype --with-glib --with-gobject --with-cairo --with-icu --with-graphite2 CPPFLAGS="-Werror -fprofile-arcs -ftest-coverage" LDFLAGS=-lgcov
  - make
  - make check
after_success:
  - rm -f src/.libs/NONE.gcov # coveralls chokes on this
  - coveralls
after_failure:
  - true
after_script:
  - true
notifications:
  irc: "irc.freenode.org#harfbuzz"
  email: harfbuzz@lists.freedesktop.org
