# Linux Build Configuration for Travis
sudo: false # Use Travis docker infrastructure
language: cpp
compiler:
  - clang
  - gcc
env:
  global:
    - CPPFLAGS=""
    - CFLAGS="-Werror --coverage"
    - CXXFLAGS="-Werror --coverage"
    - LDFLAGS="--coverage"
install:
  - pip install --user nose
  - pip install --user cpp-coveralls # for coveralls.io code coverage tracking
  - export PATH=$HOME/.local/bin:$PATH # Make sure we can find the above Python packages
script:
  - NOCONFIGURE=1 ./autogen.sh
  - ./configure --with-freetype --with-glib --with-gobject --with-cairo --with-icu --with-graphite2
  - make && make check && { rm -f src/.libs/NONE.gcov; touch src/NONE; test $CC != gcc || coveralls; }
notifications:
  irc: "irc.freenode.org#harfbuzz"
  email: harfbuzz@lists.freedesktop.org

addons:
  apt:
    packages:
      - pkg-config # for autogen.sh
      - ragel
      - gtk-doc-tools
      - libfreetype6-dev # for font function
      - libglib2.0-dev # for font functions / tests / utils
      - libcairo2-dev # for utils
      - libicu-dev # for extra unicode functions
      - libgraphite2-dev # for extra shapers
      - # libgirepository1.0-dev # for gobject-introspection
